['all']
root = 'C:\AIND\code\HSFPpreprocess\'
calibration_data = 'C:\AIND\output_data\BigTiffs2023-08-29T09_57_35.8840448-07_00\'
raw_data = 'C:\AIND\output_data\BigTiffs2023-08-10T11_50_10.0447360-07_00\'