['all']
root = 'C:\AIND\code\HSFPpreprocess\'
calibration_data = 'C:\AIND\output_data\BigTiffs2023-07-19T11_31_08.0860800-07_00\'
raw_data = 'C:\AIND\output_data\BigTiffs2023-07-19T11_41_07.3182208-07_00'