['all']
root = 'C:\AIND\code\HSFPpreprocess\legacyCode_pre2024\'
calibration_data = 'C:\AIND\output_data\BigTiffs2024-11-19T09_55_11.0083456-08_00\'
raw_data = 'Z:\\smrithi.sunil\\data-upload\\HSFP_741062_2024-11-07_12-42-06\\fib'