['all']
root = 'C:\AIND\code\HSFPpreprocess\legacyCode_pre2024\'
calibration_data = 'C:\AIND\output_data\BigTiffs2024-11-26T09_31_40.5431680-08_00\'
raw_data = 'Z:\smrithi.sunil\data-upload\HSFP_753086_2024-11-21_11-26-27'