['all']
root = 'C:\AIND\code\HSFPpreprocess\'
calibration_data = 'C:\AIND\output_data\BigTiffs2023-08-16T09_47_39.2912896-07_00\'
raw_data = 'C:\AIND\output_data\BigTiffs2023-08-16T10_00_41.6919680-07_00\'